### ISSUE TITLE
Material entity can't be resize so it limit the visibility range

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#489]
Material entities get created with as a 0.1 wide cube.
So if you parent that to a significantly large model (let say 100m wide)
when you reach that model for the first time, the material are not applied until
we reach the distance to draw allow a 0.1 wide cube to be rendered. Which is not matching the render distance for the parent entity.
Minimally we would like to have the dimension editable to address that problem and make it with a similar size than the parent.
But I wonder if that would be very intuitive.
Maybe it should get the parent size systematically.

examle:
Expected (or what you get after have been very closed):
![image](https://user-images.githubusercontent.com/60075796/85972105-000bd180-b99d-11ea-90dd-f6a178b9aa3f.png)

Here what I get after a relaod next a clear cache:
![image](https://user-images.githubusercontent.com/60075796/85972145-19148280-b99d-11ea-8a09-89dcb20b566e.png)
I have to get very close to have the material effective

**Comment by HifiExperiments** [comment]
Hm, this is supposed to work.  Although the dimensions of the material entity itself can’t change, its “queryAACube” is supposed to enlarge to include its parent so that the server still sends it even though it is small.

Can you create a small script that showcases the issue?

**Comment by AleziaKurdis** [comment]
Here's a test that can be done to reproduce it:
download this json:
http://metaverse.bashora.com/scripts/hytrion/TEST_ENTITY_MATERIAL_SIZE.json
On a domain, import that json
this will generate a blue "shape" cube with and a material entity already parented to it. 
(the cube is actually "red" but it turns "blue" because of the material entity)
now go very far from this cube (1500m)
and do "Edit > Reload Content"
The cube is now red since the material is not applied (I suspect this is because it's too small to be part of the rendering)
I would have expected that the cube would be still blue.

Before the "reload content":
![image](https://user-images.githubusercontent.com/60075796/89248487-e1bd7500-d5dd-11ea-962d-eed667a02b0d.png)

After the "reload content":
![image](https://user-images.githubusercontent.com/60075796/89248442-c3577980-d5dd-11ea-9c51-2c5416ad41b9.png)

**Comment by HifiExperiments** [comment]
I wasn't able to reproduce this on latest master.  it's possible that it's been fixed in the past few months by my entity update fixes (perhaps the issue was a missing render update to apply the material, as opposed to a visibility range issue). @AleziaKurdis does it still repro for you?

**Comment by AleziaKurdis** [comment]
Still reproducable:

![image](https://user-images.githubusercontent.com/60075796/110015380-cb050b00-7cf1-11eb-87ae-4695c6684b79.png)

![image](https://user-images.githubusercontent.com/60075796/110015396-cf312880-7cf1-11eb-8d63-b6558e8fb480.png)

the material is not rendered (suspected to be too small for that distance. It might need to have the scale matching its parent dimensions to stay effective in those case where you just load it for the first time from far away.)

**Comment by AleziaKurdis** [comment]
It seems however start to draw from a quite reasonable distance but there is a gap compared to the visibility of the object itself.
Here it's only a cub of 10 X 10 X 10... but if this was a mountain,  the results would have been more problematic.

**Comment by HifiExperiments** [comment]
ok so I think I see what the problem is, but I'm not sure what the best solution is yet.  materials DO resize their bounds (actually, just their queryAACube) to contain their parents.  this is done in `MaterialEntityItem::calculateInitialQueryAACube`.  however, before the entity server even checks the queryAACube, it culls based on octree element.  this means that a material entity with a large queryAACube could get placed in a small octree element, which would be culled before we even check the queryAACube.  the fix is probably to force material entities into larger octree elements, but only on the server.  on the client, the visibility range of the material entity doesn't matter, so we DO want it to be in the smallest element

**Comment by AleziaKurdis** [comment]
When this resizing happens exactly, is it when we parent it? 
Is resizing the dimensions too could solve the problem?

**Comment by HifiExperiments** [comment]
the queryAACube is automatically resized when it is parented, yeah.  this should be possible to solve on the server without any need to manually control the dimensions (especially since that would mess with projected materials, or procedural materials).  it will just require a bit of work to figure out the right place to do it.

**Comment by AleziaKurdis** [comment]
-
